name: ci-release-dry-run

on:
  push:
    branches:
      - bugfix-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          dryRun: true
          pat: ok
          registryUrl: https://marketplace.visualstudio.com

      - run: mkdir -p ./artefacts
      - run: cp ./*.vsix ./artefacts
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: ./artefacts